clone_folder: c:\gopath\src\github.com\kubernetes-incubator/cri-tools
image: Visual Studio 2017

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - docker version
  - copy c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\mingw32-make.exe c:\bin\make.exe
  - powershell hack/install-kubelet-windows.ps1

build: off

test_script:
  - ps: |
      make

