clone_folder: c:\gopath\src\github.com\kubernetes-incubator/cri-tools
image: Visual Studio 2017

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - docker version
  - choco upgrade chocolatey
  - choco install -y make
  - hack/install-kubelet-windows.cmd

build: off

test_script:
  - make

