language: go

go:
  - "1.11.1"

os:
  - linux
  - windows

go_import_path: github.com/kubernetes-sigs/cri-tools

services:
  - docker

before_script:
  - |
    (
      set -Eeuo pipefail
      if [ "$TRAVIS_OS_NAME" == "windows" ]; then
        hack/install-docker.ps1
        hack/install-kubelet.ps1
      else
        hack/install-docker.sh
        hack/install-kubelet.sh
      fi
    )

install:
  - make install.tools

jobs:
  include:
    - stage: Static check
      script:
        - make lint
        - make gofmt
    - stage: Build
      script:
        -  if [ "$TRAVIS_OS_NAME" == "linux" ]; then make release; fi
    - stage: Test
      script:
        - make
        - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo env PATH=$PATH GOPATH=$GOPATH hack/run-critest.sh; fi
